apiVersion: v1
data:
  mapRoles: |
   - groups:
   	  - system:masters
   	   rolearn: arn:aws:iam::413510603806:role/UdacityFlaskDeployCBKubectlRole
   	   username: build   
   - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::413510603806:role/eksctl-eksctl-demo-nodegroup-ng-f-NodeInstanceRole-PCMHSW99OHDM
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-02T08:19:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1551"
  uid: 82ac16c1-35ab-4a0b-ba0e-069a006edf60
